language: cpp

os:
  - linux
  # - osx

compiler:
  - gcc
  - clang

env:
  - AUTOTOOLS=yes COVERAGE=yes BUILD=shared
  - AUTOTOOLS=no COVERAGE=yes BUILD=shared
  - AUTOTOOLS=yes COVERAGE=yes BUILD=static
  - AUTOTOOLS=no COVERAGE=yes BUILD=static

script: ./script/ci-build-libsass
before_install: ./script/ci-install-deps
install: ./script/ci-install-compiler
after_success: ./script/ci-report-coverage
